name: Post Merge Worfklow
on:
  pull_request:
    types: [closed]
permissions:
  pull-requests: write
jobs:
  Merge:
    name: After Merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "You have merged $PR_URL successfully!!"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
  closed:
    name: After Closed
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "You have closed/cancelled $PR_URL successfully!!"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}